"""
Comprehensive Seed script for the Synova Insurance backend database.
Populates:
- 14 Leading Insurers across Motor, Health, and Term Life.
- 10+ Motor Insurance Products with Add-ons & Pricing Rules.
- 15+ Health Insurance Products with Maternity, OPD, Cashless Hospital networks.
- 15+ Term Life Insurance Products with Riders & Terms.
- Demo User & Digital Insurance Vault with Active, Expiring, and Expired policies.

Run: python -m seed_data  (from apps/backend/)
"""
from datetime import datetime, timedelta
from app.db.postgres.session import SessionLocal, engine
from app.db.postgres.base import Base
from app.core.security import hash_password
from app.models.insurer_model import Insurer
from app.models.insurance_product_model import InsuranceProduct
from app.models.pricing_rule_model import PricingRule
from app.models.pricing_factor_model import PricingFactor
from app.models.add_on_model import AddOn
from app.models.user_model import User
from app.models.policy_model import Policy
from app.models.policy_version_model import PolicyVersion
from app.models.application_model import Application
from app.models.notification_model import Notification
from app.models.provider_model import InsurerProvider
from app.models.payment_model import PaymentOrder, PaymentTransaction

def seed_database(force: bool = False):
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        existing_count = db.query(InsuranceProduct).count()
        if existing_count > 0 and not force:
            print(f"[INFO] Backend database already contains {existing_count} products. Skipping re-seed.")
            return

        print("Resetting and seeding comprehensive insurance database...")
        # Clear existing tables for fresh seed
        db.query(PaymentTransaction).delete()
        db.query(PaymentOrder).delete()
        db.query(Notification).delete()
        db.query(PolicyVersion).delete()
        db.query(Policy).delete()
        db.query(Application).delete()
        db.query(AddOn).delete()
        db.query(PricingRule).delete()
        db.query(PricingFactor).delete()
        db.query(InsuranceProduct).delete()
        db.query(InsurerProvider).delete()
        db.query(Insurer).delete()
        db.query(User).delete()
        db.commit()
        insurers_data = [
            # Multi-line & Motor
            {"name": "ICICI Lombard General Insurance", "code": "icici_lombard", "description": "India's leading private general insurer with 98.4% claim settlement ratio and 11,000+ cashless network."},
            {"name": "HDFC ERGO General Insurance", "code": "hdfc_ergo", "description": "Trusted protection with 24x7 customer support, instant paperless claim approval, and wide network."},
            {"name": "Tata AIG General Insurance", "code": "tata_aig", "description": "Tata heritage brand providing comprehensive motor, health, and travel protection with zero hassle."},
            {"name": "Acko General Insurance", "code": "acko", "description": "Tech-first digital insurer offering zero commission direct-to-consumer transparent pricing."},
            {"name": "Bajaj Allianz General Insurance", "code": "bajaj_allianz", "description": "Joint venture between Bajaj Finserv and Allianz SE offering smart drive and health solutions."},

            # Health Insurance Specialists
            {"name": "Niva Bupa Health Insurance", "code": "niva_bupa", "description": "Specialized health insurer with unlimited reset benefits, zero room rent capping, and 10,500+ hospitals."},
            {"name": "Star Health and Allied Insurance", "code": "star_health", "description": "India's first standalone health insurer with largest in-house claims network of 14,000+ hospitals."},
            {"name": "Care Health Insurance", "code": "care_health", "description": "Comprehensive health protection for families, senior citizens, and specialized critical illness treatments."},
            {"name": "Aditya Birla Health Insurance", "code": "aditya_birla", "description": "Health insurance with chronic disease management, 100% health returns reward program, and day 1 coverage."},

            # Term Life Insurance Specialists
            {"name": "Max Life Insurance", "code": "max_life", "description": "India's benchmark life insurer with 99.51% claim settlement ratio and comprehensive pure term plans."},
            {"name": "HDFC Life Insurance", "code": "hdfc_life", "description": "Pioneering life insurer offering flexible payment options, critical illness riders, and whole life cover."},
            {"name": "ICICI Prudential Life Insurance", "code": "icici_pru", "description": "Industry leader in term insurance with return of premium options and smart exit benefits."},
            {"name": "Tata AIA Life Insurance", "code": "tata_aia", "description": "Top-tier term life protection with vital wellness discounts, 99.01% settlement ratio, and express claim service."},
            {"name": "Bajaj Allianz Life Insurance", "code": "bajaj_life", "description": "Innovative life insurance solutions tailored for young professionals, breadwinners, and families."},
        ]

        insurers = [Insurer(name=d["name"], code=d["code"], description=d["description"], active=True) for d in insurers_data]
        db.add_all(insurers)
        db.flush()

        ins_map = {i.code: i.id for i in insurers}

        # --- 2. Insurer Automation Providers (Mock Portals) ---
        providers = [
            InsurerProvider(code="insurer_a", name="ICICI Lombard", website_url="http://localhost:8001", automation_enabled=True, active=True),
            InsurerProvider(code="insurer_b", name="Acko Drive", website_url="http://localhost:8002", automation_enabled=True, active=True),
            InsurerProvider(code="insurer_c", name="TATA AIG", website_url="http://localhost:8003", automation_enabled=True, active=True),
            InsurerProvider(code="insurer_d", name="HDFC Ergo", website_url="http://localhost:8004", automation_enabled=True, active=True),
        ]
        db.add_all(providers)
        db.flush()

        # --- 3. PRODUCTS CATALOG (10+ Motor, 15+ Health, 15+ Term) ---
        products_data = [
            # ================= MOTOR INSURANCE (11 Products) =================
            {
                "insurer_id": ins_map["icici_lombard"],
                "name": "ICICI Lombard Elevate Comprehensive Motor",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Zero depreciation bumper-to-bumper cover with 24x7 priority roadside towing and engine protector.",
                "base_rate": 3.0,
                "minimum_premium": 850.0,
                "default_coverage_amount": 890000.0,
                "coverage_amount_min": 200000.0,
                "coverage_amount_max": 3500000.0,
                "premium_frequency": "annual",
                "rating": 4.9,
                "claim_settlement_ratio": "98.4%",
                "features_json": ["Zero Depreciation on all parts", "24x7 Roadside Assistance within 30 mins", "Cashless claims at 7,800+ garages", "Consumables & Engine Shield included"],
                "exclusions_json": ["Drunk driving damages", "Consequential mechanical wear and tear"],
                "riders_json": ["Zero Dep", "Engine Protect", "Key Replacement", "Return to Invoice"],
            },
            {
                "insurer_id": ins_map["hdfc_ergo"],
                "name": "HDFC ERGO DriveSecure Optima Plus",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Premium bumper-to-bumper vehicle insurance with overnight repairs guarantee and zero deductibles.",
                "base_rate": 2.8,
                "minimum_premium": 920.0,
                "default_coverage_amount": 875000.0,
                "coverage_amount_min": 200000.0,
                "coverage_amount_max": 4000000.0,
                "premium_frequency": "annual",
                "rating": 4.8,
                "claim_settlement_ratio": "98.1%",
                "features_json": ["Overnight repair commitment", "Zero NCB loss on 1 claim", "8,200+ Cashless Network", "Emergency hotel stay & cab reimbursement"],
                "exclusions_json": ["War / Nuclear risks", "Unlicensed driver"],
                "riders_json": ["Zero Dep", "NCB Protect", "Emergency Hotel Stay"],
            },
            {
                "insurer_id": ins_map["tata_aig"],
                "name": "Tata AIG AutoSecure Total Protection",
                "insurance_type": "motor",
                "category": "motor",
                "description": "High IDV valuation plan with return to invoice, key replacement, and tyre damage cover.",
                "base_rate": 3.2,
                "minimum_premium": 890.0,
                "default_coverage_amount": 880000.0,
                "coverage_amount_min": 150000.0,
                "coverage_amount_max": 5000000.0,
                "premium_frequency": "annual",
                "rating": 4.8,
                "claim_settlement_ratio": "98.0%",
                "features_json": ["Full Invoice value payout on total loss", "Tyre & Rim damage covered", "7,500+ Garages", "Free pickup & drop for servicing"],
                "exclusions_json": ["Normal wear and tear", "Commercial use of private car"],
                "riders_json": ["Return to Invoice", "Tyre Secure", "Zero Dep"],
            },
            {
                "insurer_id": ins_map["acko"],
                "name": "ACKO Direct Smart Drive",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Direct zero-commission digital car insurance with 1-hour doorstep instant claim pickup.",
                "base_rate": 2.5,
                "minimum_premium": 699.0,
                "default_coverage_amount": 820000.0,
                "coverage_amount_min": 100000.0,
                "coverage_amount_max": 2500000.0,
                "premium_frequency": "annual",
                "rating": 4.7,
                "claim_settlement_ratio": "97.8%",
                "features_json": ["Zero paperwork 1-hour claim dispatch", "No middleman commission discount", "Digital claims via app", "Free towing up to 50 km"],
                "exclusions_json": ["Racing and speed testing", "Driving without valid license"],
                "riders_json": ["Zero Dep", "Roadside Assistance"],
            },
            {
                "insurer_id": ins_map["bajaj_allianz"],
                "name": "Bajaj Allianz DriveSmart Comprehensive",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Telematics-enabled smart car insurance with cashback for safe driving and full zero-dep add-ons.",
                "base_rate": 2.9,
                "minimum_premium": 780.0,
                "default_coverage_amount": 850000.0,
                "coverage_amount_min": 200000.0,
                "coverage_amount_max": 3000000.0,
                "premium_frequency": "annual",
                "rating": 4.6,
                "claim_settlement_ratio": "98.2%",
                "features_json": ["Pay-how-you-drive rewards", "7,000+ Cashless Garages", "24x7 SOS emergency app button", "Hydrostatic lock engine cover"],
                "exclusions_json": ["Driving under alcohol influence"],
                "riders_json": ["DriveSmart OBD", "Zero Dep", "Engine Shield"],
            },
            {
                "insurer_id": ins_map["icici_lombard"],
                "name": "ICICI Lombard Standalone Own Damage Shield",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Standalone Own Damage cover for vehicles with active 3-year or 5-year third-party liability.",
                "base_rate": 2.2,
                "minimum_premium": 550.0,
                "default_coverage_amount": 750000.0,
                "coverage_amount_min": 100000.0,
                "coverage_amount_max": 2000000.0,
                "premium_frequency": "annual",
                "rating": 4.7,
                "claim_settlement_ratio": "98.4%",
                "features_json": ["Standalone OD for multi-year TP owners", "Fire, theft & accidental damage", "Full NCB transfer discount"],
                "exclusions_json": ["Third party liability (requires existing TP cover)"],
                "riders_json": ["Zero Dep", "Consumables"],
            },
            {
                "insurer_id": ins_map["tata_aig"],
                "name": "Tata AIG Sapphire Plus Commercial & Fleet",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Commercial passenger and fleet vehicle insurance with key loss, daily allowance, and zero dep.",
                "base_rate": 3.5,
                "minimum_premium": 1200.0,
                "default_coverage_amount": 1200000.0,
                "coverage_amount_min": 300000.0,
                "coverage_amount_max": 6000000.0,
                "premium_frequency": "annual",
                "rating": 4.7,
                "claim_settlement_ratio": "98.0%",
                "features_json": ["Daily downtime allowance during repair", "Loss of personal baggage", "24x7 Fleet manager support"],
                "exclusions_json": ["Overloading vehicle"],
                "riders_json": ["Daily Allowance", "Emergency Transport"],
            },
            {
                "insurer_id": ins_map["acko"],
                "name": "ACKO SuperDrive Two-Wheeler Comprehensive",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Instant two-wheeler & electric scooter insurance with zero inspection and full theft cover.",
                "base_rate": 1.8,
                "minimum_premium": 399.0,
                "default_coverage_amount": 120000.0,
                "coverage_amount_min": 25000.0,
                "coverage_amount_max": 500000.0,
                "premium_frequency": "annual",
                "rating": 4.8,
                "claim_settlement_ratio": "97.8%",
                "features_json": ["Instant bike quote with only reg number", "Battery & Motor cover for EVs", "Zero inspection renewal"],
                "exclusions_json": ["Racing on public roads"],
                "riders_json": ["EV Battery Shield", "Helmet Cover"],
            },
            {
                "insurer_id": ins_map["hdfc_ergo"],
                "name": "HDFC ERGO RideSure Two-Wheeler Shield",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Two wheeler comprehensive policy with personal accident cover up to ₹15 Lakh for owner driver.",
                "base_rate": 2.0,
                "minimum_premium": 450.0,
                "default_coverage_amount": 140000.0,
                "coverage_amount_min": 30000.0,
                "coverage_amount_max": 600000.0,
                "premium_frequency": "annual",
                "rating": 4.7,
                "claim_settlement_ratio": "98.1%",
                "features_json": ["15 Lakh mandatory PA cover", "Cashless repair across 3,500+ bike garages", "Engine seizure protection"],
                "exclusions_json": ["Driving under intoxication"],
                "riders_json": ["PA Cover 15L", "Zero Dep Bike"],
            },
            {
                "insurer_id": ins_map["bajaj_allianz"],
                "name": "Bajaj Allianz DriveProtect Third-Party Liability",
                "insurance_type": "motor",
                "category": "motor",
                "description": "Mandatory government third-party liability insurance covering third-party injury, death and property damage.",
                "base_rate": 1.0,
                "minimum_premium": 3416.0,
                "default_coverage_amount": 750000.0,
                "coverage_amount_min": 750000.0,
                "coverage_amount_max": 750000.0,
                "premium_frequency": "annual",
                "rating": 4.5,
                "claim_settlement_ratio": "98.2%",
                "features_json": ["Unlimited Third-Party bodily injury cover", "Third-party property damage up to ₹7.5 Lakh", "100% legal compliance"],
                "exclusions_json": ["Damage to own car"],
                "riders_json": ["PA Cover 15L"],
            },

            # ================= HEALTH INSURANCE (16 Products) =================
            {
                "insurer_id": ins_map["niva_bupa"],
                "name": "Niva Bupa ReAssure 2.0 Platinum",
                "insurance_type": "health",
                "category": "health",
                "description": "Groundbreaking health plan with unlimited lock-the-clock entry age premium and unlimited reset benefit.",
                "minimum_premium": 850.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 10000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.1%",
                "cashless_hospitals_count": 10500,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "No Limit (Any Room Category)",
                "plan_type": "Individual & Family Floater",
                "features_json": ["Lock the Clock: Premium fixed at entry age until 1st claim", "ReAssure Forever: Unlimited sum insured restore", "10,500+ Cashless Hospitals", "Pre & Post Hospitalization (60/180 Days)"],
                "exclusions_json": ["Cosmetic / aesthetic surgeries", "Adventure sports injuries without safety gear"],
                "riders_json": ["OPD Care Addon", "Hospital Daily Cash"],
            },
            {
                "insurer_id": ins_map["star_health"],
                "name": "Star Health Comprehensive Super Shield",
                "insurance_type": "health",
                "category": "health",
                "description": "Zero room rent capping, normal & C-section maternity cover, and newborn baby coverage from Day 1.",
                "minimum_premium": 790.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 25000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "98.7%",
                "cashless_hospitals_count": 14000,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "Single Private AC Room",
                "plan_type": "Family Floater",
                "features_json": ["Maternity cover up to ₹1 Lakh (Normal & C-Section)", "Newborn vaccination & cover from Day 1", "14,000+ Hospital Network (Largest in India)", "Annual free health checkup for all adults"],
                "exclusions_json": ["Self-inflicted injury", "Alcohol rehabilitation"],
                "riders_json": ["Maternity Super Cover", "Bariatric Surgery Rider"],
            },
            {
                "insurer_id": ins_map["care_health"],
                "name": "Care Health Supreme Optima Plus",
                "insurance_type": "health",
                "category": "health",
                "description": "Complete healthcare protection with unlimited automatic recharge and annual health checkup.",
                "minimum_premium": 740.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 50000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "98.9%",
                "cashless_hospitals_count": 11200,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": False,
                "critical_illness_covered": True,
                "room_rent_limit": "Single Private AC Room",
                "plan_type": "Individual & Family Floater",
                "features_json": ["150% Cumulative No Claim Bonus", "Unlimited automatic recharge on partial exhaustion", "Daycare procedures: 540+ covered", "Air ambulance coverage up to ₹5 Lakh"],
                "exclusions_json": ["Diagnostic tests without hospitalization", "Weight loss treatments"],
                "riders_json": ["Care Shield (Inflation Protect)", "Everyday Care OPD"],
            },
            {
                "insurer_id": ins_map["hdfc_ergo"],
                "name": "HDFC ERGO Optima Secure Global",
                "insurance_type": "health",
                "category": "health",
                "description": "4X coverage with 2X cover from Day 1, plus 100% Secure benefit and global emergency medical assistance.",
                "minimum_premium": 950.0,
                "default_coverage_amount": 1500000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 20000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.0%",
                "cashless_hospitals_count": 12000,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "No Capping on Room Category",
                "plan_type": "Family Floater",
                "features_json": ["2X Cover Instantly from Day 1 at zero extra cost", "100% Restore Benefit after every claim", "Zero deduction on non-medical consumables (gloves, PPE)", "Emergency treatment outside India covered"],
                "exclusions_json": ["Alternative non-allopathic unapproved therapies", "War zone claims"],
                "riders_json": ["Global Treatment Rider", "Critical Illness Addon"],
            },
            {
                "insurer_id": ins_map["aditya_birla"],
                "name": "Aditya Birla Activ Health Platinum Enhanced",
                "insurance_type": "health",
                "category": "health",
                "description": "Rewards program earning up to 100% of your premium back for healthy living + Day 1 chronic disease cover.",
                "minimum_premium": 890.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 20000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "98.5%",
                "cashless_hospitals_count": 10000,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "Single Private AC Room",
                "plan_type": "Individual & Family Floater",
                "features_json": ["Earn up to 100% HealthReturns™ by tracking steps", "Day 1 cover for Diabetes, Hypertension, Asthma & Cholesterol", "Mental health & psychiatric care covered", "OPD consultations & prescribed medicines"],
                "exclusions_json": ["Cosmetic treatments", "Self-harm"],
                "riders_json": ["Chronic Management Booster", "Maternity Plus"],
            },
            {
                "insurer_id": ins_map["icici_lombard"],
                "name": "ICICI Lombard Health AdvantEdge Elite",
                "insurance_type": "health",
                "category": "health",
                "description": "Comprehensive individual and family health shield with no co-pay and global emergency medical cover.",
                "minimum_premium": 820.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 30000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "98.6%",
                "cashless_hospitals_count": 9800,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "No Sub-limit",
                "plan_type": "Individual & Family Floater",
                "features_json": ["Zero co-pay at any age", "Pre-hospitalization 60 days, Post 180 days", "Bariatric surgery and organ donor expenses covered", "Cashless claims approved within 30 minutes"],
                "exclusions_json": ["Genetic testing without symptoms", "Sterility treatments"],
                "riders_json": ["BeFit OPD Card", "Compassionate Visit Rider"],
            },
            {
                "insurer_id": ins_map["acko"],
                "name": "ACKO Platinum Health Unlimited",
                "insurance_type": "health",
                "category": "health",
                "description": "Zero deduction policy covering 100% of hospital bill with zero room rent limit and zero copay.",
                "minimum_premium": 650.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 1000000.0,
                "coverage_amount_max": 100000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "98.2%",
                "cashless_hospitals_count": 11000,
                "waiting_period_months": 0,
                "maternity_covered": False,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "Any Room Category / Suite",
                "plan_type": "Individual & Family Floater",
                "features_json": ["Zero waiting period option", "100% bill payout with zero deductions for consumables", "Dedicated relationship doctor allocated", "Doorstep medicine delivery"],
                "exclusions_json": ["Routine dental without trauma"],
                "riders_json": ["Global Critical Illness"],
            },
            {
                "insurer_id": ins_map["star_health"],
                "name": "Star Health Senior Citizens Red Carpet",
                "insurance_type": "health",
                "category": "health",
                "description": "Specialized health protection for seniors aged 60-75 without mandatory pre-policy medical checkup.",
                "minimum_premium": 1450.0,
                "default_coverage_amount": 750000.0,
                "coverage_amount_min": 300000.0,
                "coverage_amount_max": 2500000.0,
                "premium_frequency": "monthly",
                "rating": 4.7,
                "claim_settlement_ratio": "98.7%",
                "cashless_hospitals_count": 14000,
                "waiting_period_months": 12,
                "maternity_covered": False,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "1% of Sum Insured",
                "plan_type": "Senior Citizen Individual/Floater",
                "features_json": ["No pre-insurance medical test required", "Pre-existing diseases covered after only 12 months", "Outpatient consultations at network hospitals", "Dialysis charges covered up to ₹1,000/sitting"],
                "exclusions_json": ["Non-allopathic treatment uncertified"],
                "riders_json": ["Senior OPD Shield"],
            },
            {
                "insurer_id": ins_map["care_health"],
                "name": "Care Health Freedom Diabetic & Cardiac Plan",
                "insurance_type": "health",
                "category": "health",
                "description": "Dedicated health cover designed for individuals with pre-existing Diabetes, High BP, and BMI conditions.",
                "minimum_premium": 1150.0,
                "default_coverage_amount": 500000.0,
                "coverage_amount_min": 300000.0,
                "coverage_amount_max": 1000000.0,
                "premium_frequency": "monthly",
                "rating": 4.6,
                "claim_settlement_ratio": "98.9%",
                "cashless_hospitals_count": 11200,
                "waiting_period_months": 24,
                "maternity_covered": False,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "Twin Sharing Room",
                "plan_type": "Individual",
                "features_json": ["No medical tests up to age 50", "Dialysis & diabetic foot ulcer covered", "Annual health checkup tailored for diabetic care"],
                "exclusions_json": ["Self-injury", "Unapproved experimental therapy"],
                "riders_json": ["OPD Diabetes Care"],
            },
            {
                "insurer_id": ins_map["niva_bupa"],
                "name": "Niva Bupa Health Companion Family",
                "insurance_type": "health",
                "category": "health",
                "description": "Value-packed family health floater covering up to 4 adults and 5 children with refill benefits.",
                "minimum_premium": 680.0,
                "default_coverage_amount": 750000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 1500000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "99.1%",
                "cashless_hospitals_count": 10500,
                "waiting_period_months": 24,
                "maternity_covered": False,
                "opd_covered": False,
                "critical_illness_covered": True,
                "room_rent_limit": "Single Private Room",
                "plan_type": "Family Floater",
                "features_json": ["Animal bite vaccine vaccination coverage", "Organ donor expenses covered", "Alternative treatments (AYUSH) in recognized hospitals", "Direct claim settlement via Niva Bupa team"],
                "exclusions_json": ["Cosmetic treatments"],
                "riders_json": ["Hospital Cash", "Critical Illness Addon"],
            },
            {
                "insurer_id": ins_map["aditya_birla"],
                "name": "Aditya Birla Activ Fit Young Professionals",
                "insurance_type": "health",
                "category": "health",
                "description": "Specialized health plan for individuals under 35 with gym membership rewards and up to 50% NCB.",
                "minimum_premium": 580.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 10000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "98.5%",
                "cashless_hospitals_count": 10000,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "Single Private AC Room",
                "plan_type": "Individual",
                "features_json": ["10% early bird discount on sign-up before age 35", "50% Cumulative bonus for claim-free year", "Free fitness tracking & mental wellness app access"],
                "exclusions_json": ["Sports injuries in professional competitions"],
                "riders_json": ["Fitness Booster Rider"],
            },
            {
                "insurer_id": ins_map["tata_aig"],
                "name": "Tata AIG MediCare Premier Comprehensive",
                "insurance_type": "health",
                "category": "health",
                "description": "High sum insured plan with global emergency coverage, maternity cover, and consumable protection.",
                "minimum_premium": 920.0,
                "default_coverage_amount": 2000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 50000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "98.0%",
                "cashless_hospitals_count": 8500,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "No Limit",
                "plan_type": "Family Floater",
                "features_json": ["Maternity coverage up to ₹50,000", "Bariatric surgery and robotic treatments covered", "Prolonged hospitalization convalescence allowance", "High-end diagnostics covered (PET, MRI)"],
                "exclusions_json": ["Unproven experimental drugs"],
                "riders_json": ["Global Emergency Assistance"],
            },
            {
                "insurer_id": ins_map["bajaj_allianz"],
                "name": "Bajaj Allianz Health Guard Gold",
                "insurance_type": "health",
                "category": "health",
                "description": "Standard comprehensive family healthcare with preventive wellness checks and maternity cover.",
                "minimum_premium": 710.0,
                "default_coverage_amount": 750000.0,
                "coverage_amount_min": 300000.0,
                "coverage_amount_max": 5000000.0,
                "premium_frequency": "monthly",
                "rating": 4.7,
                "claim_settlement_ratio": "98.2%",
                "cashless_hospitals_count": 7500,
                "waiting_period_months": 36,
                "maternity_covered": True,
                "opd_covered": False,
                "critical_illness_covered": True,
                "room_rent_limit": "Single Private Room",
                "plan_type": "Family Floater",
                "features_json": ["Maternity expenses covered after 36 months", "Ayurvedic and Homeopathic treatments in recognized hospitals", "Bariatric surgery for severe morbid obesity"],
                "exclusions_json": ["Cosmetic treatments"],
                "riders_json": ["Hospital Cash", "Critical Illness Addon"],
            },
            {
                "insurer_id": ins_map["star_health"],
                "name": "Star Health Women Care Super Insurance",
                "insurance_type": "health",
                "category": "health",
                "description": "Specialized health protection designed for women covering ante-natal, delivery, and female-specific critical illnesses.",
                "minimum_premium": 880.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 10000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "98.7%",
                "cashless_hospitals_count": 14000,
                "waiting_period_months": 24,
                "maternity_covered": True,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "Single Private AC Room",
                "plan_type": "Individual Woman / Family Floater",
                "features_json": ["Ante-natal and maternity care from Day 1 of policy", "Congenital internal and external defect coverage for baby", "Breast and cervical cancer accelerated payout", "Zero medical test for women under 45"],
                "exclusions_json": ["Elective cosmetic procedures"],
                "riders_json": ["Newborn Intensive Care Shield"],
            },
            {
                "insurer_id": ins_map["care_health"],
                "name": "Care Health Critical Illness Total Protection",
                "insurance_type": "health",
                "category": "health",
                "description": "Lump-sum cash payout plan covering 32 major critical illnesses including Cancer, Heart Attack, Stroke and Renal Failure.",
                "minimum_premium": 520.0,
                "default_coverage_amount": 2500000.0,
                "coverage_amount_min": 1000000.0,
                "coverage_amount_max": 10000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "98.9%",
                "cashless_hospitals_count": 11200,
                "waiting_period_months": 3,
                "maternity_covered": False,
                "opd_covered": False,
                "critical_illness_covered": True,
                "room_rent_limit": "No Limit (Lump Sum)",
                "plan_type": "Individual",
                "features_json": ["100% lump sum payout upon first diagnosis of 32 illnesses", "No need to submit hospital bills for payout", "Second medical opinion from world-leading oncology experts", "Quick 30-day survival period"],
                "exclusions_json": ["Pre-existing critical illness diagnosed within 90 days"],
                "riders_json": ["Major Organ Transplant Booster"],
            },
            {
                "insurer_id": ins_map["niva_bupa"],
                "name": "Niva Bupa Senior First Gold",
                "insurance_type": "health",
                "category": "health",
                "description": "Comprehensive healthcare for parents and senior citizens with no mandatory test and reasonable copay.",
                "minimum_premium": 1380.0,
                "default_coverage_amount": 1000000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 2500000.0,
                "premium_frequency": "monthly",
                "rating": 4.7,
                "claim_settlement_ratio": "99.1%",
                "cashless_hospitals_count": 10500,
                "waiting_period_months": 24,
                "maternity_covered": False,
                "opd_covered": True,
                "critical_illness_covered": True,
                "room_rent_limit": "Single Private Room",
                "plan_type": "Senior Citizen",
                "features_json": ["No pre-policy test up to age 70", "Cataract and knee replacement covered", "Annual health checkup at home"],
                "exclusions_json": ["Cosmetic treatments"],
                "riders_json": ["Home Nursing Care Addon"],
            },

            # ================= TERM LIFE INSURANCE (15 Products) =================
            {
                "insurer_id": ins_map["max_life"],
                "name": "Max Life Smart Secure Plus (1 Cr Cover)",
                "insurance_type": "term",
                "category": "term",
                "description": "Flagship pure term plan with India's highest 99.51% settlement ratio, terminal illness payout, and return of premium.",
                "minimum_premium": 680.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 50000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.51%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["100% payout on diagnosis of Terminal Illness", "Special Exit Value: Option to get all premiums back at age 65", "99.51% Claim Settlement Ratio (Industry Benchmark)", "1-Day Express Claim settlement commitment"],
                "exclusions_json": ["Suicide within first 12 months from policy inception"],
                "riders_json": ["Accidental Death Benefit (₹1 Cr)", "Critical Illness Benefit (64 illnesses)", "Waiver of Premium Plus"],
            },
            {
                "insurer_id": ins_map["hdfc_life"],
                "name": "HDFC Life Click 2 Protect Super",
                "insurance_type": "term",
                "category": "term",
                "description": "Flexible term protection with life stage coverage increase (marriage, child birth) and comprehensive accidental rider.",
                "minimum_premium": 720.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 50000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.39%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["Life stage auto-upgrade (Increase cover by 50% on marriage/baby)", "Smart exit option to reclaim all paid premiums", "Monthly regular income option for family", "Instant online medical test booking"],
                "exclusions_json": ["Suicide within first policy year"],
                "riders_json": ["Income Benefit on Accidental Disability", "Critical Illness Plus (36 conditions)"],
            },
            {
                "insurer_id": ins_map["icici_pru"],
                "name": "ICICI Prudential iProtect Smart",
                "insurance_type": "term",
                "category": "term",
                "description": "All-in-one term insurance offering 34 critical illnesses lump sum payout and terminal illness cover.",
                "minimum_premium": 650.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 50000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.17%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["34 Critical Illnesses covered with immediate cash payout", "Permanent disability waiver of all future premiums", "Coverage up to 99 years of age (Whole Life Option)", "Special 10% discount on first year premium for salaried women"],
                "exclusions_json": ["Suicide in first 12 months"],
                "riders_json": ["Accidental Death Rider", "Accelerated Critical Illness Cover"],
            },
            {
                "insurer_id": ins_map["tata_aia"],
                "name": "Tata AIA Sampoorna Raksha Supreme",
                "insurance_type": "term",
                "category": "term",
                "description": "Comprehensive term plan with Vitality wellness rewards offering up to 15% annual premium discount for staying active.",
                "minimum_premium": 710.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 50000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.01%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["Tata AIA Vitality: Earn up to 15% premium discount for staying fit", "Whole life cover up to age 100", "Top-up life cover option during milestones", "Terminal illness advance payout"],
                "exclusions_json": ["Suicide within 12 months of commencement"],
                "riders_json": ["Tata AIA Vitality Protect", "Accidental Death & Dismemberment"],
            },
            {
                "insurer_id": ins_map["bajaj_life"],
                "name": "Bajaj Allianz Life eTouch Smart Term",
                "insurance_type": "term",
                "category": "term",
                "description": "Affordable online pure term insurance with high sum assured rebate and waiver of premium on accidental disability.",
                "minimum_premium": 590.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 30000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "98.8%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["Low-cost online pure term protection", "Terminal Illness benefit built-in", "Attractive discount for non-smokers and healthy individuals", "Flexible death benefit payout (Lump sum or Monthly income)"],
                "exclusions_json": ["Self-inflicted death in 1st year"],
                "riders_json": ["Accidental Death Benefit", "Critical Illness Cover"],
            },
            {
                "insurer_id": ins_map["max_life"],
                "name": "Max Life Critical Illness & Disability Term Shield",
                "insurance_type": "term",
                "category": "term",
                "description": "Pure term plan with comprehensive early-stage and late-stage cancer and heart attack coverage.",
                "minimum_premium": 890.0,
                "default_coverage_amount": 15000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 50000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.51%",
                "max_entry_age": 60,
                "smoker_allowed": True,
                "features_json": ["64 Critical Illness conditions covered with lump sum cash", "No need to submit medical bills for payout", "Cover continues even after critical illness claim"],
                "exclusions_json": ["Suicide in 1st year", "Pre-existing illness within 90 days"],
                "riders_json": ["Accidental Disability Rider"],
            },
            {
                "insurer_id": ins_map["hdfc_life"],
                "name": "HDFC Life Saral Jeevan Bima (Standard Term)",
                "insurance_type": "term",
                "category": "term",
                "description": "Standardized government-prescribed simple pure term insurance with easy eligibility and simple documentation.",
                "minimum_premium": 420.0,
                "default_coverage_amount": 2500000.0,
                "coverage_amount_min": 500000.0,
                "coverage_amount_max": 2500000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "99.39%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["Standard terms and conditions approved by IRDAI", "Affordable low entry barrier for all income groups", "Simple medical evaluation"],
                "exclusions_json": ["Suicide within 12 months"],
                "riders_json": ["Accidental Benefit"],
            },
            {
                "insurer_id": ins_map["icici_pru"],
                "name": "ICICI Prudential Precious Life (High Risk Individuals)",
                "insurance_type": "term",
                "category": "term",
                "description": "First-of-its-kind term insurance specially designed for individuals with pre-existing medical conditions like Diabetes and Heart Surgeries.",
                "minimum_premium": 1150.0,
                "default_coverage_amount": 7500000.0,
                "coverage_amount_min": 2500000.0,
                "coverage_amount_max": 20000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "99.17%",
                "max_entry_age": 60,
                "smoker_allowed": True,
                "features_json": ["Specifically designed for individuals with Diabetes, Cholesterol, Heart Stents", "Comprehensive life cover after thorough underwriting", "Terminal illness benefit included"],
                "exclusions_json": ["Suicide in 1st year"],
                "riders_json": ["Accidental Death"],
            },
            {
                "insurer_id": ins_map["tata_aia"],
                "name": "Tata AIA Maha Raksha Supreme Ultra",
                "insurance_type": "term",
                "category": "term",
                "description": "High-value term insurance designed for HNIs and business owners with up to ₹10 Crore sum assured and Keyman Insurance.",
                "minimum_premium": 1850.0,
                "default_coverage_amount": 30000000.0,
                "coverage_amount_min": 20000000.0,
                "coverage_amount_max": 100000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.01%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["High Sum Assured rebate for ₹2 Crore+ coverage", "Keyman & Partnership business insurance eligible", "Priority underwriting and concierge claim manager"],
                "exclusions_json": ["Suicide in 1st year"],
                "riders_json": ["HNI Accidental Shield", "Executive Health Rider"],
            },
            {
                "insurer_id": ins_map["bajaj_life"],
                "name": "Bajaj Allianz Life Return of Premium Term (TROP)",
                "insurance_type": "term",
                "category": "term",
                "description": "Term insurance plan that returns 100% of all paid premiums back to you upon policy maturity.",
                "minimum_premium": 1250.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 30000000.0,
                "premium_frequency": "monthly",
                "rating": 4.7,
                "claim_settlement_ratio": "98.8%",
                "max_entry_age": 55,
                "smoker_allowed": True,
                "features_json": ["100% of total premiums paid returned if you survive the policy term", "Life cover of ₹1 Crore+ throughout the tenure", "Tax benefits under Section 80C and 10(10D)"],
                "exclusions_json": ["Suicide in 1st year"],
                "riders_json": ["Critical Illness Rider", "Accidental Benefit"],
            },
            {
                "insurer_id": ins_map["max_life"],
                "name": "Max Life Whole Life 99 Guard",
                "insurance_type": "term",
                "category": "term",
                "description": "Lifetime coverage ensuring wealth inheritance and guaranteed family legacy payout until age 99.",
                "minimum_premium": 1450.0,
                "default_coverage_amount": 15000000.0,
                "coverage_amount_min": 10000000.0,
                "coverage_amount_max": 50000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.51%",
                "max_entry_age": 60,
                "smoker_allowed": True,
                "features_json": ["Guaranteed death benefit payout up to age 99", "Create generational wealth legacy for children", "Pay till age 60 and enjoy coverage till age 99"],
                "exclusions_json": ["Suicide in 1st year"],
                "riders_json": ["Accidental Death", "Critical Illness Rider"],
            },
            {
                "insurer_id": ins_map["hdfc_life"],
                "name": "HDFC Life 3D Plus Comprehensive Term",
                "insurance_type": "term",
                "category": "term",
                "description": "Protects against the 3Ds of life: Death, Disease, and Disability with complete waiver of premium.",
                "minimum_premium": 810.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 40000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.39%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["3D Protection: Death, Disease (Critical Illness), and Disability", "Waiver of premium upon diagnosis of critical illness or disability", "Accelerated cancer cover"],
                "exclusions_json": ["Suicide in 1st year"],
                "riders_json": ["Accidental Disability", "Cancer Shield"],
            },
            {
                "insurer_id": ins_map["icici_pru"],
                "name": "ICICI Prudential Smart Income Term",
                "insurance_type": "term",
                "category": "term",
                "description": "Provides monthly regular salary income to your family for 10, 20 or 30 years in your absence.",
                "minimum_premium": 780.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 30000000.0,
                "premium_frequency": "monthly",
                "rating": 4.8,
                "claim_settlement_ratio": "99.17%",
                "max_entry_age": 60,
                "smoker_allowed": True,
                "features_json": ["Guaranteed increasing monthly income (10% increase every year) to family", "Replaces breadwinner's lost monthly income", "Inflation-protected family support"],
                "exclusions_json": ["Suicide in 1st year"],
                "riders_json": ["Accidental Death"],
            },
            {
                "insurer_id": ins_map["tata_aia"],
                "name": "Tata AIA Life Protect Pro Salaried Shield",
                "insurance_type": "term",
                "category": "term",
                "description": "Tailored pure term insurance for corporate salaried employees with corporate discount and instant digital issuance.",
                "minimum_premium": 620.0,
                "default_coverage_amount": 10000000.0,
                "coverage_amount_min": 5000000.0,
                "coverage_amount_max": 35000000.0,
                "premium_frequency": "monthly",
                "rating": 4.9,
                "claim_settlement_ratio": "99.01%",
                "max_entry_age": 65,
                "smoker_allowed": True,
                "features_json": ["10% corporate employee discount on first year premium", "Digital KYC with zero paper visits", "Tax deduction under 80C up to ₹1.5 Lakh/yr"],
                "exclusions_json": ["Suicide in 1st year"],
                "riders_json": ["Accidental Death", "Critical Illness"],
            },
            {
                "insurer_id": ins_map["bajaj_life"],
                "name": "Bajaj Allianz Life POS Goal Suraksha",
                "insurance_type": "term",
                "category": "term",
                "description": "Over-the-counter paperless term protection with guaranteed issuance and minimal health questions.",
                "minimum_premium": 480.0,
                "default_coverage_amount": 5000000.0,
                "coverage_amount_min": 2500000.0,
                "coverage_amount_max": 10000000.0,
                "premium_frequency": "monthly",
                "rating": 4.7,
                "claim_settlement_ratio": "98.8%",
                "max_entry_age": 55,
                "smoker_allowed": True,
                "features_json": ["Point-of-Sale (POS) instant policy certificate issuance", "No medical tests required for standard profiles", "Affordable protection for young families"],
                "exclusions_json": ["Suicide in 1st year"],
                "riders_json": ["Accidental Death"],
            },
        ]

        products = [InsuranceProduct(**p, active=True) for p in products_data]
        db.add_all(products)
        db.flush()

        print(f"Seeded {len(products)} Insurance Products across Motor, Health, and Term!")

        # --- 4. Dynamic Pricing Rules for Motor Products ---
        motor_prods = [p for p in products if p.insurance_type == "motor"]
        for prod in motor_prods:
            r1 = PricingRule(product_id=prod.id, name="Base OD Premium", rule_type="base",
                             expression={"op": "mul", "args": [{"var": "vehicle.idv"}, {"const": (prod.base_rate or 3.0) / 100.0}]}, priority=10, active=True)
            r2 = PricingRule(product_id=prod.id, name="Vehicle Age Loading", rule_type="loading",
                             expression={"op": "mul", "args": [{"var": "vehicle.age_years"}, {"const": 400}]}, priority=20, active=True)
            r3 = PricingRule(product_id=prod.id, name="NCB Discount", rule_type="discount",
                             expression={"op": "mul", "args": [
                                 {"op": "mul", "args": [{"var": "vehicle.idv"}, {"const": (prod.base_rate or 3.0) / 100.0}]},
                                 {"op": "div", "args": [{"var": "driver.ncb_percent"}, {"const": 100}]}
                             ]}, priority=30, active=True)
            db.add_all([r1, r2, r3])

        # --- Add-ons for Products ---
        addons_data = [
            ("Zero Depreciation", 0.003, 1450.0),
            ("24x7 Roadside Assistance", 0.0, 499.0),
            ("Engine & Gearbox Protect", 0.0015, 1200.0),
            ("Consumables Cover", 0.0, 650.0),
            ("Return to Invoice (RTI)", 0.002, 1800.0),
            ("Tyre Secure Protection", 0.0, 750.0),
            ("Key Replacement", 0.0, 350.0),
        ]
        for prod in motor_prods[:6]:
            for name, rate, amt in addons_data:
                db.add(AddOn(product_id=prod.id, name=name, premium_factor=rate, flat_amount=amt, active=True))

        # --- 5. Demo User Account ---
        demo_user = User(
            full_name="Hariharan Murugesan",
            email="hariharan@synova.ai",
            hashed_password=hash_password("Demo@1234"),
            role="customer",
            is_active=True,
        )
        db.add(demo_user)
        db.flush()

        # --- 6. Digital Policy Vault Seed (Motor, Health, Term Life) ---
        now = datetime.now()
        demo_vault_policies = [
            # Motor Policy (Active)
            Policy(
                customer_id=demo_user.id,
                product_id=products[0].id,
                policy_number="SYN-MOT-2025-884920",
                insurance_type="motor",
                insurer_name="ICICI Lombard General Insurance",
                product_name="ICICI Lombard Elevate Comprehensive Motor",
                status="active",
                premium=13450.0,
                coverage_amount=890000.0,
                idv=890000.0,
                deductible=1000.0,
                start_date=now - timedelta(days=120),
                end_date=now + timedelta(days=245),
                vehicle_registration="KA-01-MJ-4092",
                vehicle_make="Hyundai",
                vehicle_model="Creta SX (2022)",
                ncb_percent=25.0,
                addons="Zero Depreciation, 24x7 Roadside Assistance, Engine Protect",
                notes="Active comprehensive vehicle protection with bumper-to-bumper cover.",
                active=True,
            ),
            # Health Policy (Active)
            Policy(
                customer_id=demo_user.id,
                product_id=products[11].id,
                policy_number="SYN-HLT-2025-449102",
                insurance_type="health",
                insurer_name="Niva Bupa Health Insurance",
                product_name="Niva Bupa ReAssure 2.0 Platinum",
                status="active",
                premium=11500.0,
                coverage_amount=1000000.0,
                idv=1000000.0,
                deductible=0.0,
                start_date=now - timedelta(days=90),
                end_date=now + timedelta(days=275),
                addons="Unlimited Reset, Maternity Plus, OPD Care",
                notes="Family floater policy covering self, spouse and 1 child across 10,500+ hospitals.",
                active=True,
            ),
            # Term Life Policy (Active)
            Policy(
                customer_id=demo_user.id,
                product_id=products[27].id,
                policy_number="SYN-TRM-2024-110293",
                insurance_type="term",
                insurer_name="Max Life Insurance",
                product_name="Max Life Smart Secure Plus (1 Cr Cover)",
                status="active",
                premium=8400.0,
                coverage_amount=10000000.0,
                idv=10000000.0,
                deductible=0.0,
                start_date=now - timedelta(days=300),
                end_date=now + timedelta(days=365 * 29),  # 30-year term
                addons="Accidental Death Benefit (₹1 Cr), Critical Illness (64 Conditions)",
                notes="Pure term life security with ₹1 Crore sum assured and terminal illness benefit.",
                active=True,
            ),
            # Health Policy (Expiring Soon - 14 days)
            Policy(
                customer_id=demo_user.id,
                product_id=products[12].id,
                policy_number="SYN-HLT-2024-991823",
                insurance_type="health",
                insurer_name="Star Health and Allied Insurance",
                product_name="Star Health Comprehensive Super Shield",
                status="active",
                premium=9800.0,
                coverage_amount=750000.0,
                idv=750000.0,
                deductible=0.0,
                start_date=now - timedelta(days=351),
                end_date=now + timedelta(days=14),
                addons="Maternity Super Cover, Zero Room Rent",
                notes="Annual renewal due in 14 days. Eligible for instant renewal on Synova.",
                active=True,
            ),
        ]
        db.add_all(demo_vault_policies)
        db.flush()

        for pol in demo_vault_policies:
            db.add(PolicyVersion(policy_id=pol.id, version=1, effective_from=pol.start_date, data={"policy_number": pol.policy_number, "document_url": f"/policies/download/{pol.id}"}))

        # Initial Notification
        db.add(Notification(
            customer_id=demo_user.id,
            subject="Welcome to Synova Multi-Category Marketplace",
            message="Explore over 40+ dynamic insurance plans across Motor, Health, and Term Life with AI natural language search.",
            notification_type="system",
        ))

        db.commit()
        print("[SUCCESS] Successfully seeded 14 Insurers, 41 Products, Pricing Rules, Add-ons, and Vault Policies!")
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
        raise
    finally:
        db.close()


if __name__ == '__main__':
    seed_database(force=True)
